import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/header/Header';
import hero from '../public/images/hero.jpg';
import ProductThumbnail from '../components/product/ProductThumbnail';

import lingerie from '../public/images/lingerie.png';
import nightwear from '../public/images/nightwear.png';
import newIn from '../public/images/new-in.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Peach and Petal - Lingerie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="relative w-full">
        <Image src={hero} layout="responsive" objectFit="contain" />
        <div className="absolute left-20 top-10 flex justify-center flex-col">
          <p
            className=" text-white text-5xl mb-4"
            style={{
              fontFamily: 'Playfair',
            }}
          >
            Summer Sale
          </p>
          <p className=" text-white mb-4">
            Save up to 15% on selected items with code SUMMER
          </p>
          <p
            style={{
              fontFamily: 'Playfair',
            }}
            className="border bg-red-300 border-red-300 text-red-300 w-fit px-6 py-1 text-s rounded-full text-black"
          >
            Shop Sale
          </p>
        </div>
      </div>
      <div className="flex justify-evenly m-24 gap-x-10">
        <ProductThumbnail title="Lingerie" image={lingerie} />
        <ProductThumbnail title="Nightwear" image={nightwear} />
        <ProductThumbnail title="New In" image={newIn} />
      </div>
    </div>
  );
}
